name: ValueCoCreator
favicon: null
layout_spectrum: 0.34713
typography_spectrum: 0.31166
title: Value CoCreator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0f0f0f'
    - '#ac4d6f'
    - '#e5a219'
    - '#00abdf'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
