name: ValueCoCreator
favicon: null
layout_spectrum: 0.73806
typography_spectrum: 0.97412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e646e'
    - '#4ea9bb'
    - '#55b8cb'
    - '#4698a6'
    - '#3b818d'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
