name: ValueCoCreator
favicon: null
layout_spectrum: 0.5685975481756032
typography_spectrum: 0.83556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#ffffff'
    - '#e46591'
    - '#ffcf36'
    - '#03c4fc'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
